#!/bin/sh
# /etc/vmware-tools/scripts/vmware/network which
# otherwise runs deprecated "service networking stop|start"
# Put into /etc/init.d/network and make executable.
#

case "$1" in
stop)
    ifdown -a
    ;;
start)
    ifup -a
    ;;
restart)
    ifdown -a
    ifup -a
    ;;
esac
